name: custom_lint
version: 0.5.3
description: Lint rules are a powerful way to improve the maintainability of a project. Custom Lint allows package authors and developers to easily write custom lint rules.
repository: https://github.com/invertase/dart_custom_lint
issue_tracker: https://github.com/invertase/dart_custom_lint/issues

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  analyzer: ">=5.12.0 <7.0.0"
  analyzer_plugin: ^0.11.3
  args: ^2.4.2
  async: ^2.11.0
  ci: ^0.1.0
  cli_util: ^0.4.0
  collection: ^1.17.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  meta: ^1.9.1
  package_config: ^2.1.0
  path: ^1.8.3
  pub_semver: ^2.1.4
  pubspec_parse: ^1.2.3
  rxdart: ^0.27.7
  uuid: ^4.0.0
  yaml: ^3.1.2

dev_dependencies:
  ansi_styles: ^0.3.2+1
  benchmark_harness: ^2.2.2
  build_runner: ^2.4.6
  file: ^7.0.0
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  test: ^1.24.6
  test_process: ^2.1.0

executables:
  custom_lint: custom_lint
